require("ismiabbas.plugins-setup")
require('ismiabbas.core.options')
require('ismiabbas.core.keymaps')
require('ismiabbas.core.colorschemes')
require('ismiabbas.plugins.comments')
require('ismiabbas.plugins.nvim-tree')
require('ismiabbas.plugins.lualine')
